# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44fa70854c8fddf0aae65ae4f0057dccd23c6ecd441bc8e2b4da3a74f2b779a83f701408435838c3aa46e032966002bf5f2e6d62113ae549e757168957d9c366

test:
  secret_key_base: 610dea42f64d356b9ce3a442993772c2ac05e48b0c52748f84214867477379688e70fff866363da178d491b5ccff81dc99db11d01ae1341952a27e1033d505a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
